events {}

http {
    upstream api_servers {
        server api:5000;
    }

    upstream analytics_servers {
        server analytics:5001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api_servers/;
        }

        location /analytics/ {
            proxy_pass http://analytics_servers/;
        }
    }
}
