graph TD
    Client((Client App)) -.->|HTTP 3000| FrontendNginx[Frontend Nginx Container]
    Client -.->|HTTP 8000| MainNginx[Primary Nginx Load Balancer]
    
    subgraph Frontend Subystem
        FrontendNginx <-->|Serves Static Files| React[React SPA Interface]
        FrontendNginx -.->|Proxies /api| MainNginx
    end

    subgraph Service Tier
        MainNginx <-->|/api| API(Python Flask API Service)
        MainNginx <-->|/analytics| Analytics(Python Analytics API)
    end
    
    subgraph Storage Tier
        API -->|Insert URL| PrimaryDb[(PostgreSQL Primary Database)]
        PrimaryDb -.->|Async Replication| ReplicaDb[(PostgreSQL Read Replica)]
        API <-->|Redis Lookups| Redis[(Redis Speed Cache)]
        API -->|Fallback Cache Miss| ReplicaDb
    end
    
    subgraph Event Streaming Pipeline
        API -->|Publish url_clicks| Kafka{{Kafka Event Broker}}
        API -->|Publish system_logs| Kafka
        Worker(Python Ingestion Worker) -->|Consume Topics| Kafka
    end
    
    subgraph Analytics Data Layer
        Worker -->|Insert click metadata| AnalyticsDb[(PostgreSQL Analytics Database)]
        Worker -->|Insert system logs| AnalyticsDb
        Analytics <-->|Select Metrics| AnalyticsDb
    end
